name: Little Rock Plumbers
favicon: null
layout_spectrum: 0.29619151377119124
typography_spectrum: 0.327496871817857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.20011773519217968
  lightness: 0.5873129246756434
  saturation: 0.9858848415315151
  rhythmicContrast: 0.9728656189981848
purpose: []
