name: Little Rock Plumbers 501-666-9483
favicon: null
layout_spectrum: 0.48145
typography_spectrum: 0.327496871817857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
